In [38]:
# https://iamtrask.github.io/2015/07/12/basic-python-network/

In [1]:
import numpy as np

In [3]:
# sigmoid function
def nonlin(x, deriv = False):
    if(deriv == True):
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

In [4]:
# input dataset
X = np.array([ [0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1] ])

In [5]:
# output dataset
y = np.array([[0,0,1,1]]).T

In [6]:
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

In [7]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

In [8]:
for iter in range(10000):
    
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(10, syn0))
    
    # how much did we miss?
    l1_error = y - l1
    
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1, True)
    
    # update weights
    syn0 += np.dot(l0.T, l1_delta)

ValueError: operands could not be broadcast together with shapes (4,1) (3,1) 

In [9]:
print ("Output After Training: ")
print (l1)

Output After Training: 
[[1.59821083e-01]
 [9.87949077e-01]
 [4.55018303e-05]]


In [20]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

for iter in range(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print ("Output After Training:")
print (l1)
print("syn0 :")
print(syn0)


Output After Training:
[[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]
syn0 :
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]


In [35]:
# 3 layer NN

In [22]:
def nonlin(x, deriv = False):
    if(deriv == True):
        return x *(1-x)
    return 1/(1+np.exp(-x))

In [23]:
X = np.array([[0,0,1],
             [0,1,1],
             [1,0,1],
             [1,1,1]])

In [24]:
y = np.array([[0],
            [1],
            [1],
            [0]])

In [25]:
np.random.seed(1)

In [26]:
# randomly initilize weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [48]:
for j in range(600000):
    
    #Feed forward through layers 0, 1, 2
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
    
    # How much did we miss by?
    l2_error = y - l2
    
    if (j % 100000) == 0:
        print("Error:" +
             str(np.mean(np.abs(l2_error))))
    
    # In what direction is the target value?
    l2_delta = l2_error*nonlin(l2, True)
    
    # How much did each l1 value contrubute to the l2 error?
    l1_error = l2_delta.dot(syn1.T)
    
    # In what direction is the target l1?
    l1_delta = l1_error * nonlin(l1, True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

Error:0.0006540033605276702
Error:0.0006289970464479002
Error:0.0006066349182809881
Error:0.0005864826471159187
Error:0.0005681995279676114
Error:0.0005515140512744458


In [44]:
print(l2)

[[5.47016778e-04]
 [9.99349433e-01]
 [9.99365936e-01]
 [7.84367223e-04]]


In [116]:
print(nonlin(l2, True))

[[0.00259893]
 [0.00326717]
 [0.00297399]
 [0.00385263]]


In [46]:
print(syn1)

[[ -8.47655452]
 [  8.38351592]
 [-11.35357567]
 [  9.38068262]]


## 

In [47]:
print(np.exp(2))

7.38905609893065
