In [38]:
# https://iamtrask.github.io/2015/07/12/basic-python-network/

In [122]:
import numpy as np

In [123]:
# sigmoid function
def nonlin(x, deriv = False):
    if(deriv == True):
        return x * (1 - x)
    return 1 / (1 + np.exp(-x))

In [124]:
# input dataset
X = np.array([ [0,0,1],
              [0,1,1],
              [1,0,1],
              [1,1,1] ])

In [125]:
# output dataset
y = np.array([[0,0,1,1]]).T

In [126]:
# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

In [127]:
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

In [128]:
for iter in range(10000):
    
    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(10, syn0))
    
    # how much did we miss?
    l1_error = y - l1
    
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1, True)
    
    # update weights
    syn0 += np.dot(l0.T, l1_delta)

ValueError: operands could not be broadcast together with shapes (4,1) (3,1) 

In [130]:
print ("Output After Training: ")
print (l1)

Output After Training: 
[[1.59821083e-01]
 [9.87949077e-01]
 [4.55018303e-05]]


In [132]:
import numpy as np

# sigmoid function
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))
    
# input dataset
X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])
    
# output dataset            
y = np.array([[0,0,1,1]]).T

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)

# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,1)) - 1

for iter in range(10000):

    # forward propagation
    l0 = X
    l1 = nonlin(np.dot(l0,syn0))

    # how much did we miss?
    l1_error = y - l1

    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)

    # update weights
    syn0 += np.dot(l0.T,l1_delta)

print ("Output After Training:")
print (l1)
print("syn0 :")
print(syn0)


Output After Training:
[[0.00966449]
 [0.00786506]
 [0.99358898]
 [0.99211957]]
syn0 :
[[ 9.67299303]
 [-0.2078435 ]
 [-4.62963669]]


In [35]:
# 3 layer NN

In [107]:
def nonlin(x, deriv = False):
    if(deriv == True):
        return x *(1-x)
    return 1/(1+np.exp(-x))

In [108]:
X = np.array([[0,0,1],
             [0,1,1],
             [1,0,1],
             [1,1,1]])

In [109]:
y = np.array([[0],
            [1],
            [1],
            [0]])

In [110]:
np.random.seed(1)

In [111]:
# randomly initilize weights with mean 0
syn0 = 2*np.random.random((3,4)) - 1
syn1 = 2*np.random.random((4,1)) - 1

In [121]:
for j in range(60000):
    
    #Feed forward through layers 0, 1, 2
    l0 = X
    l1 = nonlin(np.dot(l0, syn0))
    l2 = nonlin(np.dot(l1, syn1))
    
    # How much did we miss by?
    l2_error = y - l2
    
    if (j % 10000) == 0:
        print("Error:" +
             str(np.mean(np.abs(l2_error))))
    
    # In what direction is the target value?
    l2_delta = l2_error*nonlin(l2, True)
    
    # How much did each l1 value contrubute to the l2 error?
    l1_error = l2_delta.dot(syn1.T)
    
    # In what direction is the target l1?
    l1_delta = l1_error * nonlin(l1, True)
    
    syn1 += l1.T.dot(l2_delta)
    syn0 += l0.T.dot(l1_delta)

Error:0.003183502385874827
Error:0.0029323063422830717
Error:0.002731506418210508
Error:0.0025663172400400254
Error:0.0024273760867576715
Error:0.002308431160626394


In [120]:
print(l1)

[[7.26191199e-01 1.16411907e-01 9.26183940e-01 9.97110310e-01]
 [1.66762801e-01 3.92990161e-04 1.66519465e-02 8.96576847e-01]
 [9.96229372e-01 8.95211165e-01 2.23120442e-02 8.38385421e-01]
 [9.52239003e-01 2.48589483e-02 3.07990327e-05 1.15301801e-01]]


In [116]:
print(nonlin(l2, True))

[[0.00259893]
 [0.00326717]
 [0.00297399]
 [0.00385263]]


In [115]:
print(syn1)

[[ -6.96765763]
 [  7.14101949]
 [-10.31917382]
 [  7.86128405]]


## 

In [140]:
print(np.exp(2))

7.38905609893065
